//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageDeployer.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings_pt_br {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings_pt_br() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageDeployer.Lang.GlobalStrings.pt-br", typeof(GlobalStrings_pt_br).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferramenta de build do DotNet não encontrada..
        /// </summary>
        public static string Error_DotNetNotFound {
            get {
                return ResourceManager.GetString("Error_DotNetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao processar o repositório existente.
        /// </summary>
        public static string Error_HandleExistingRepository {
            get {
                return ResourceManager.GetString("Error-HandleExistingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao processar o novo repositório:.
        /// </summary>
        public static string Error_HandleNewRepository {
            get {
                return ResourceManager.GetString("Error-HandleNewRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro - O formato de nome do repositório é inválido.
        /// </summary>
        public static string Error_InvalidRepositoryFormat {
            get {
                return ResourceManager.GetString("Error-InvalidRepositoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro no loop principal:.
        /// </summary>
        public static string Error_MainLoop {
            get {
                return ResourceManager.GetString("Error-MainLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBuild não encontrado..
        /// </summary>
        public static string Error_MSBuildNotFound {
            get {
                return ResourceManager.GetString("Error_MSBuildNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao processar o repositório:.
        /// </summary>
        public static string Error_ProcessingRepository {
            get {
                return ResourceManager.GetString("Error-ProcessingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicação do projeto falhou..
        /// </summary>
        public static string Error_ProjectPublishFailed {
            get {
                return ResourceManager.GetString("Error_ProjectPublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositório não encontrado.
        /// </summary>
        public static string Error_RepositoryNotFound {
            get {
                return ResourceManager.GetString("Error-RepositoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando build no projeto....
        /// </summary>
        public static string Info_BuildingProject {
            get {
                return ResourceManager.GetString("Info-BuildingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clonando repositório....
        /// </summary>
        public static string Info_CloningRepository {
            get {
                return ResourceManager.GetString("Info-CloningRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiando arquivos para a pasta de destino da publicação....
        /// </summary>
        public static string Info_CopyingFilesToThePublishDestinationFolder {
            get {
                return ResourceManager.GetString("Info-CopyingFilesToThePublishDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicação finalizada!.
        /// </summary>
        public static string Info_DeploymentFinish {
            get {
                return ResourceManager.GetString("Info-DeploymentFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciada a transferência dos arquivos para a pasta de publicação..
        /// </summary>
        public static string Info_FileCopyStarted {
            get {
                return ResourceManager.GetString("Info-FileCopyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos transferidos com sucesso..
        /// </summary>
        public static string Info_FilesCopiedSuccessfully {
            get {
                return ResourceManager.GetString("Info-FilesCopiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build do projeto iniciada..
        /// </summary>
        public static string Info_ProjectBuildStarted {
            get {
                return ResourceManager.GetString("Info-ProjectBuildStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build do projeto realizada com sucesso..
        /// </summary>
        public static string Info_ProjectBuiltSuccessfully {
            get {
                return ResourceManager.GetString("Info-ProjectBuiltSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto publicado com sucesso..
        /// </summary>
        public static string Info_ProjectPublishedSuccessfully_ {
            get {
                return ResourceManager.GetString("Info_ProjectPublishedSuccessfully ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicação do projeto iniciada..
        /// </summary>
        public static string Info_ProjectPublishStarted_ {
            get {
                return ResourceManager.GetString("Info_ProjectPublishStarted ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasta de publicação encontrada em:.
        /// </summary>
        public static string Info_PublishFolderFound {
            get {
                return ResourceManager.GetString("Info-PublishFolderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicando projeto....
        /// </summary>
        public static string Info_PublishingProject_ {
            get {
                return ResourceManager.GetString("Info_PublishingProject ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositório clonado com sucesso..
        /// </summary>
        public static string Info_RepositoryClonedSuccessfully {
            get {
                return ResourceManager.GetString("Info-RepositoryClonedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizando a seguinte pasta para publicação:.
        /// </summary>
        public static string Info_UsingPublishFolder {
            get {
                return ResourceManager.GetString("Info-UsingPublishFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Option_Exit {
            get {
                return ResourceManager.GetString("Option-Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo repositório.
        /// </summary>
        public static string Option_NewRepository {
            get {
                return ResourceManager.GetString("Option-NewRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o caminho da pasta de destino da publicação.
        /// </summary>
        public static string Prompt_EnterDestinationFolder {
            get {
                return ResourceManager.GetString("Prompt-EnterDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o token do GitHub do novo repositório.
        /// </summary>
        public static string Prompt_EnterGitHubToken {
            get {
                return ResourceManager.GetString("Prompt-EnterGitHubToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o nome do novo repositório (Projeto/Repositorio).
        /// </summary>
        public static string Prompt_EnterRepositoryName {
            get {
                return ResourceManager.GetString("Prompt-EnterRepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressione qualquer tecla para finalizar.
        /// </summary>
        public static string Prompt_PressToFinish {
            get {
                return ResourceManager.GetString("Prompt-PressToFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma branch.
        /// </summary>
        public static string Prompt_SelectBranch {
            get {
                return ResourceManager.GetString("Prompt-SelectBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um repositório existente ou crie uma nova configuração de repositório.
        /// </summary>
        public static string Prompt_SelectOrCreateRepositoryConfig {
            get {
                return ResourceManager.GetString("Prompt-SelectOrCreateRepositoryConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um projeto.
        /// </summary>
        public static string Prompt_SelectProject {
            get {
                return ResourceManager.GetString("Prompt-SelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja utilizar a configuração Release? (Caso não, a configuração Debug será utilizada).
        /// </summary>
        public static string Prompt_UseReleaseConfiguration_ {
            get {
                return ResourceManager.GetString("Prompt_UseReleaseConfiguration ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja salvar a configuração do novo repositório?.
        /// </summary>
        public static string Prompt_WishToSaveConfig {
            get {
                return ResourceManager.GetString("Prompt-WishToSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja salvar a configuração de publicação deste projeto?.
        /// </summary>
        public static string Prompt_WishToSavePublishConfiguration {
            get {
                return ResourceManager.GetString("Prompt-WishToSavePublishConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja utilizar a pasta de publicação existente?.
        /// </summary>
        public static string Prompt_WishToUseExistingPublishFolder {
            get {
                return ResourceManager.GetString("Prompt-WishToUseExistingPublishFolder", resourceCulture);
            }
        }
    }
}
