//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageDeployer.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings_pt_br {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings_pt_br() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageDeployer.Lang.GlobalStrings.pt-br", typeof(GlobalStrings_pt_br).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro - O formato de nome do repositório é inválido.
        /// </summary>
        public static string Error_InvalidRepositoryFormat {
            get {
                return ResourceManager.GetString("Error-InvalidRepositoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizando build no projeto....
        /// </summary>
        public static string Info_BuildingProject {
            get {
                return ResourceManager.GetString("Info-BuildingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clonando repositório....
        /// </summary>
        public static string Info_CloningRepository {
            get {
                return ResourceManager.GetString("Info-CloningRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiando arquivos para a pasta de destino da publicação....
        /// </summary>
        public static string Info_CopyingFilesToThePublishDestinationFolder {
            get {
                return ResourceManager.GetString("Info-CopyingFilesToThePublishDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build do projeto realizada com sucesso..
        /// </summary>
        public static string Info_ProjectBuiltSuccessfully {
            get {
                return ResourceManager.GetString("Info-ProjectBuiltSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositório clonado com sucesso..
        /// </summary>
        public static string Info_RepositoryClonedSuccessfully {
            get {
                return ResourceManager.GetString("Info-RepositoryClonedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo repositório.
        /// </summary>
        public static string Option_NewRepository {
            get {
                return ResourceManager.GetString("Option-NewRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o caminho da pasta de destino da publicação.
        /// </summary>
        public static string Prompt_EnterDestinationFolder {
            get {
                return ResourceManager.GetString("Prompt-EnterDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o token do GitHub do novo repositório.
        /// </summary>
        public static string Prompt_EnterGitHubToken {
            get {
                return ResourceManager.GetString("Prompt-EnterGitHubToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o nome do novo repositório (Projeto/Repositorio).
        /// </summary>
        public static string Prompt_EnterRepositoryName {
            get {
                return ResourceManager.GetString("Prompt-EnterRepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um repositório existente ou crie uma nova configuração de repositório.
        /// </summary>
        public static string Prompt_SelectOrCreateRepositoryConfig {
            get {
                return ResourceManager.GetString("Prompt-SelectOrCreateRepositoryConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja salvar a configuração do novo repositório?.
        /// </summary>
        public static string Prompt_WishToSaveConfig {
            get {
                return ResourceManager.GetString("Prompt-WishToSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja salvar a configuração de publicação deste projeto?.
        /// </summary>
        public static string Prompt_WishToSavePublishConfiguration {
            get {
                return ResourceManager.GetString("Prompt-WishToSavePublishConfiguration", resourceCulture);
            }
        }
    }
}
