//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageDeployer.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageDeployer.Lang.GlobalStrings.en", typeof(GlobalStrings_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Invalid repository name format.
        /// </summary>
        public static string Error_InvalidRepositoryFormat {
            get {
                return ResourceManager.GetString("Error-InvalidRepositoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building project....
        /// </summary>
        public static string Info_BuildingProject {
            get {
                return ResourceManager.GetString("Info-BuildingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning repository....
        /// </summary>
        public static string Info_CloningRepository {
            get {
                return ResourceManager.GetString("Info-CloningRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files to the publish destination folder....
        /// </summary>
        public static string Info_CopyingFilesToThePublishDestinationFolder {
            get {
                return ResourceManager.GetString("Info-CopyingFilesToThePublishDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project built successfully..
        /// </summary>
        public static string Info_ProjectBuiltSuccessfully {
            get {
                return ResourceManager.GetString("Info-ProjectBuiltSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository cloned successfully..
        /// </summary>
        public static string Info_RepositoryClonedSuccessfully {
            get {
                return ResourceManager.GetString("Info-RepositoryClonedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New repository.
        /// </summary>
        public static string Option_NewRepository {
            get {
                return ResourceManager.GetString("Option-NewRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the publish destination folder path.
        /// </summary>
        public static string Prompt_EnterDestinationFolder {
            get {
                return ResourceManager.GetString("Prompt-EnterDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new repository name (ProjectTeam/Repository).
        /// </summary>
        public static string Prompt_EnterGitHubToken {
            get {
                return ResourceManager.GetString("Prompt-EnterGitHubToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new repository name (ProjectTeam/Repository).
        /// </summary>
        public static string Prompt_EnterRepositoryName {
            get {
                return ResourceManager.GetString("Prompt-EnterRepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing repository or create a new repository configuration.
        /// </summary>
        public static string Prompt_SelectOrCreateRepositoryConfig {
            get {
                return ResourceManager.GetString("Prompt-SelectOrCreateRepositoryConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save this repository configuration?.
        /// </summary>
        public static string Prompt_WishToSaveConfig {
            get {
                return ResourceManager.GetString("Prompt-WishToSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save this project&apos;s publish configuration?.
        /// </summary>
        public static string Prompt_WishToSavePublishConfiguration {
            get {
                return ResourceManager.GetString("Prompt-WishToSavePublishConfiguration", resourceCulture);
            }
        }
    }
}
