//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageDeployer.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageDeployer.Lang.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error cloning/updating repository..
        /// </summary>
        public static string Error_CloningOrUpdatingRepository {
            get {
                return ResourceManager.GetString("Error_CloningOrUpdatingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotNet (build) not found..
        /// </summary>
        public static string Error_DotNetNotFound {
            get {
                return ResourceManager.GetString("Error_DotNetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while handling an existing repository.
        /// </summary>
        public static string Error_HandleExistingRepository {
            get {
                return ResourceManager.GetString("Error-HandleExistingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while handling a new repository:.
        /// </summary>
        public static string Error_HandleNewRepository {
            get {
                return ResourceManager.GetString("Error-HandleNewRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Invalid repository name format.
        /// </summary>
        public static string Error_InvalidRepositoryFormat {
            get {
                return ResourceManager.GetString("Error-InvalidRepositoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the main loop:.
        /// </summary>
        public static string Error_MainLoop {
            get {
                return ResourceManager.GetString("Error-MainLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBuild not found.
        /// </summary>
        public static string Error_MSBuildNotFound {
            get {
                return ResourceManager.GetString("Error_MSBuildNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the repository:.
        /// </summary>
        public static string Error_ProcessingRepository {
            get {
                return ResourceManager.GetString("Error-ProcessingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project build failed..
        /// </summary>
        public static string Error_ProjectPublishFailed {
            get {
                return ResourceManager.GetString("Error_ProjectPublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository not found.
        /// </summary>
        public static string Error_RepositoryNotFound {
            get {
                return ResourceManager.GetString("Error-RepositoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building project....
        /// </summary>
        public static string Info_BuildingProject {
            get {
                return ResourceManager.GetString("Info-BuildingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning repository....
        /// </summary>
        public static string Info_CloningRepository {
            get {
                return ResourceManager.GetString("Info-CloningRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files to the publish folder....
        /// </summary>
        public static string Info_CopyingFilesToThePublishDestinationFolder {
            get {
                return ResourceManager.GetString("Info-CopyingFilesToThePublishDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment finished!.
        /// </summary>
        public static string Info_DeploymentFinish {
            get {
                return ResourceManager.GetString("Info-DeploymentFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started file copy to publish folder..
        /// </summary>
        public static string Info_FileCopyStarted {
            get {
                return ResourceManager.GetString("Info-FileCopyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files copied successfully..
        /// </summary>
        public static string Info_FilesCopiedSuccessfully {
            get {
                return ResourceManager.GetString("Info-FilesCopiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project build started..
        /// </summary>
        public static string Info_ProjectBuildStarted {
            get {
                return ResourceManager.GetString("Info-ProjectBuildStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project built successfully..
        /// </summary>
        public static string Info_ProjectBuiltSuccessfully {
            get {
                return ResourceManager.GetString("Info-ProjectBuiltSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project published successfully..
        /// </summary>
        public static string Info_ProjectPublishedSuccessfully_ {
            get {
                return ResourceManager.GetString("Info_ProjectPublishedSuccessfully ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project publish started..
        /// </summary>
        public static string Info_ProjectPublishStarted_ {
            get {
                return ResourceManager.GetString("Info_ProjectPublishStarted ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish folder found at:.
        /// </summary>
        public static string Info_PublishFolderFound {
            get {
                return ResourceManager.GetString("Info-PublishFolderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing project....
        /// </summary>
        public static string Info_PublishingProject_ {
            get {
                return ResourceManager.GetString("Info_PublishingProject ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository cloned successfully..
        /// </summary>
        public static string Info_RepositoryClonedSuccessfully {
            get {
                return ResourceManager.GetString("Info-RepositoryClonedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository updated successfully..
        /// </summary>
        public static string Info_RepositoryUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("Info_RepositoryUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating repository....
        /// </summary>
        public static string Info_UpdatingRepository {
            get {
                return ResourceManager.GetString("Info-UpdatingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using publish folder:.
        /// </summary>
        public static string Info_UsingPublishFolder {
            get {
                return ResourceManager.GetString("Info-UsingPublishFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Option_Exit {
            get {
                return ResourceManager.GetString("Option-Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New branch.
        /// </summary>
        public static string Option_NewBranch {
            get {
                return ResourceManager.GetString("Option-NewBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string Option_NewProject {
            get {
                return ResourceManager.GetString("Option_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New repository.
        /// </summary>
        public static string Option_NewRepository {
            get {
                return ResourceManager.GetString("Option-NewRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the publish destination folder path.
        /// </summary>
        public static string Prompt_EnterDestinationFolder {
            get {
                return ResourceManager.GetString("Prompt-EnterDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new repository name (ProjectTeam/Repository).
        /// </summary>
        public static string Prompt_EnterGitHubToken {
            get {
                return ResourceManager.GetString("Prompt-EnterGitHubToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new repository name (ProjectTeam/Repository).
        /// </summary>
        public static string Prompt_EnterRepositoryName {
            get {
                return ResourceManager.GetString("Prompt-EnterRepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to finish.
        /// </summary>
        public static string Prompt_PressToFinish {
            get {
                return ResourceManager.GetString("Prompt-PressToFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a branch.
        /// </summary>
        public static string Prompt_SelectBranch {
            get {
                return ResourceManager.GetString("Prompt-SelectBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing branch configuration or create a new one..
        /// </summary>
        public static string Prompt_SelectOrCreateBranchConfig {
            get {
                return ResourceManager.GetString("Prompt_SelectOrCreateBranchConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing project configuration or create a new one..
        /// </summary>
        public static string Prompt_SelectOrCreateProjectConfig {
            get {
                return ResourceManager.GetString("Prompt_SelectOrCreateProjectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing repository or create a new repository configuration.
        /// </summary>
        public static string Prompt_SelectOrCreateRepositoryConfig {
            get {
                return ResourceManager.GetString("Prompt-SelectOrCreateRepositoryConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a project.
        /// </summary>
        public static string Prompt_SelectProject {
            get {
                return ResourceManager.GetString("Prompt-SelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to use the Release configuration? (If not, the Debug configuration will be used instead).
        /// </summary>
        public static string Prompt_UseReleaseConfiguration_ {
            get {
                return ResourceManager.GetString("Prompt_UseReleaseConfiguration ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save this repository configuration?.
        /// </summary>
        public static string Prompt_WishToSaveConfig {
            get {
                return ResourceManager.GetString("Prompt-WishToSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save this project&apos;s publish configuration?.
        /// </summary>
        public static string Prompt_WishToSavePublishConfiguration {
            get {
                return ResourceManager.GetString("Prompt-WishToSavePublishConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to use the existing publish folder?.
        /// </summary>
        public static string Prompt_WishToUseExistingPublishFolder {
            get {
                return ResourceManager.GetString("Prompt-WishToUseExistingPublishFolder", resourceCulture);
            }
        }
    }
}
